name: sreporter
description: A helpful dependency to send messages, reports or crash logs from your flutter app to telegram chats and discord servers.
version: 1.0.0

repository: https://github.com/smith8h/sreporter-flutter

topics:
  - reports
  - dart
  - tools
  - discord
  - telegram
  - flutter
  - logger
  - messages

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
